project:
  type: book
lang: pt


book:
  title: "Uma Introdução à Computação com Julia"
  author:
    - "Alfredo Goldman"
    - "Lucas de Sousa Rosa"
  repo-url: https://github.com/firilisinof/livro-intro-comp-julia
  downloads: [pdf]
  date: "last-modified"
  chapters:
    - index.qmd
    - 00-agradecimentos.qmd
    - 01-evolucao-computacao.qmd
    - 02-calculadora-repl.qmd
    - 03-condicionais.qmd
    - 04-funcoes-recursao.qmd
    - 05-problemas-recursao.qmd
    - 06-testes-automatizados.qmd
    - 07-while.qmd
    - 08-exercicios.qmd
    - 09-exercicios-cont.qmd
    - 10-entrada-dados.qmd
    - 11-exercicios-2.qmd
    - 12-blackjack.qmd
    - 13-blackjack-cont.qmd
    - 14-boas-praticas.qmd
    - 15-matrizes.qmd
    - 16-exercicios-3.qmd
  appendices:
    - A01-questionario.qmd

execute:
  cache: true
  freeze: auto
  daemon: 120

format:
  html:
    theme: cosmo
  pdf:
    toc: true
    number-sections: true
    colorlinks: true